# version: "3" => obsolete

services:
  db:
    image: mariadb:11.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mariadb
    networks:
      - backend

  api:
    build:
      context: ../../back_student
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      WINSTON_SOURCE_TOKEN: ${WINSTON_SOURCE_TOKEN}
      WINSTON_INVESTING_HOST: ${WINSTON_INVESTING_HOST}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend

  front:
    build:
      context: ../../front_student
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
# ⚠️ IMPORTANT: Create React App (CRA) environment variable behavior
# ------------------------------------------------------------------
# CRA does NOT read environment variables passed via `environment:` at runtime.
# All `REACT_APP_*` variables must be available at BUILD TIME to be embedded
# in the static bundle during `yarn build`.
#
# That's why we use `build.args` to pass REACT_APP_API_URL into the Dockerfile,
# so CRA can pick it up and inject it into the build.
#
# Any variables defined under `environment:` will NOT be accessible in the React app.
