name: Build and Push Docker Images to Nexus

on:
  push:
    branches:
      - master
      - feat/trigger-pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Nexus Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          registry: ${{ secrets.NEXUS_DOMAIN }}

      - name: Build and tag Frontend image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            -t ${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/front_student:${{ github.sha }} \
            -t ${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/front_student:latest \
            ./front_student

      - name: Push Frontend images (SHA + latest)
        run: |
          docker push ${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/front_student:${{ github.sha }}
          docker push ${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/front_student:latest

      - name: Build and tag Backend image
        run: |
          docker build \
            -t ${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/back_student:${{ github.sha }} \
            -t ${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/back_student:latest \
            ./back_student

      - name: Push Backend images (SHA + latest) 
        run: |
          docker push ${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/back_student:${{ github.sha }}
          docker push ${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/back_student:latest

      - name: Notify VM webhook about new images
        run: |
          curl -X POST https://cloud.flopify.fr/ \
            -H "Content-Type: application/json" \
            -d '{
              "name": "${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/front_student",
              "tag": "latest"
            }'

          curl -X POST https://cloud.flopify.fr/ \
            -H "Content-Type: application/json" \
            -d '{
              "name": "${{ secrets.NEXUS_DOMAIN }}/${{ secrets.NEXUS_REPOSITORY }}/back_student",
              "tag": "latest"
            }'
