name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Nexus Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          registry: nexus-repository.axel-martin.fr

      - name: Build Frontend Docker image
        run: |
          docker build --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} -t nexus-repository.axel-martin.fr/front_student:latest ./front_student

      - name: Push Frontend Docker image
        run: |
          docker push nexus-repository.axel-martin.fr/front_student:latest

      - name: Build Backend Docker image
        run: |
          docker build -t nexus-repository.axel-martin.fr/back_student:latest ./back_student

      - name: Push Backend Docker image
        run: |
          docker push nexus-repository.axel-martin.fr/back_student:latest
